# Generated by Django 3.2 on 2023-01-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата cоздания')),
            ],
        ),
    ]
